/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import JDBCConnection.ClientMangement;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.Account;
import model.Client;
import model.Food;
import model.History;
import model.OrderRecord;
import service.AccountService;
import service.HistoryService;

/**
 *
 * @author Admin
 */
public class CLient1 extends javax.swing.JFrame {

    /**
     * Creates new form CLient1
     */
    HistoryService historyService;
    
    AccountService accountService;
    ClientMangement clientMangement;
    private boolean runing;
    public CLient1() {
        historyService=new HistoryService();
        clientMangement=new ClientMangement();
        runing=true;
        initComponents();
        sigginDialog.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sigginDialog = new javax.swing.JDialog();
        userLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        singinButton = new javax.swing.JButton();
        passwrodField = new javax.swing.JPasswordField();
        noteLabel = new javax.swing.JLabel();
        inboxDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        serviceDialog = new javax.swing.JDialog();
        servicePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        foodTable = new javax.swing.JTable();
        OrderButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        timeField = new javax.swing.JTextField();
        inboxButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        moneyField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        serviceButton = new javax.swing.JButton();

        sigginDialog.setLocation(new java.awt.Point(100, 50));
        sigginDialog.setSize(new java.awt.Dimension(255, 200));
        sigginDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                sigginDialogWindowOpened(evt);
            }
        });

        userLabel.setText("UserName");

        passLabel.setText("PassWord");

        singinButton.setText("Đăng Nhâp");
        singinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singinButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sigginDialogLayout = new javax.swing.GroupLayout(sigginDialog.getContentPane());
        sigginDialog.getContentPane().setLayout(sigginDialogLayout);
        sigginDialogLayout.setHorizontalGroup(
            sigginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sigginDialogLayout.createSequentialGroup()
                .addGroup(sigginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sigginDialogLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(sigginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sigginDialogLayout.createSequentialGroup()
                                .addGroup(sigginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(userLabel)
                                    .addComponent(passLabel))
                                .addGap(18, 18, 18)
                                .addGroup(sigginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userNameField)
                                    .addComponent(passwrodField, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                            .addGroup(sigginDialogLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(noteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(sigginDialogLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(singinButton)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        sigginDialogLayout.setVerticalGroup(
            sigginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sigginDialogLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(sigginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(sigginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passLabel)
                    .addComponent(passwrodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(singinButton)
                .addGap(34, 34, 34))
        );

        inboxDialog.setSize(new java.awt.Dimension(336, 215));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inboxDialogLayout = new javax.swing.GroupLayout(inboxDialog.getContentPane());
        inboxDialog.getContentPane().setLayout(inboxDialogLayout);
        inboxDialogLayout.setHorizontalGroup(
            inboxDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inboxDialogLayout.createSequentialGroup()
                .addGroup(inboxDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inboxDialogLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inboxDialogLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(sendButton)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        inboxDialogLayout.setVerticalGroup(
            inboxDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inboxDialogLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sendButton)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        serviceDialog.setSize(new java.awt.Dimension(400, 300));

        servicePanel.setPreferredSize(new java.awt.Dimension(1200, 700));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Bảng giá");

        foodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(foodTable);

        OrderButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        OrderButton.setForeground(new java.awt.Color(255, 0, 0));
        OrderButton.setText("Order");
        OrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout servicePanelLayout = new javax.swing.GroupLayout(servicePanel);
        servicePanel.setLayout(servicePanelLayout);
        servicePanelLayout.setHorizontalGroup(
            servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicePanelLayout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
            .addGroup(servicePanelLayout.createSequentialGroup()
                .addGroup(servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(servicePanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(servicePanelLayout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(OrderButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        servicePanelLayout.setVerticalGroup(
            servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicePanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OrderButton)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout serviceDialogLayout = new javax.swing.GroupLayout(serviceDialog.getContentPane());
        serviceDialog.getContentPane().setLayout(serviceDialogLayout);
        serviceDialogLayout.setHorizontalGroup(
            serviceDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
            .addGroup(serviceDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(serviceDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(servicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        serviceDialogLayout.setVerticalGroup(
            serviceDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
            .addGroup(serviceDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(serviceDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(servicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setText("time");

        inboxButton.setText("Nhắn tin");
        inboxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inboxButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Đăng xuất");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Money");

        jLabel3.setText("Price");

        moneyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyFieldActionPerformed(evt);
            }
        });

        priceField.setText("7500");

        serviceButton.setText("Dịch vụ");
        serviceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(priceField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moneyField)
                            .addComponent(timeField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(serviceButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inboxButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(moneyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(serviceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(inboxButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutButton)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sigginDialogWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_sigginDialogWindowOpened
        // TODO add your handling code here:
      
    }//GEN-LAST:event_sigginDialogWindowOpened
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
       // sigginDialog.setVisible(true);
    }//GEN-LAST:event_formMouseClicked
    public String getTime(double time)
    {
        int temp=(int)(time-(int)time)*60;
        time=(int)time;
        return Double.toString(time)+":"+Integer.toString(temp);
    }
    
    private void singinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singinButtonActionPerformed
        // TODO add your handling code here:
        accountService=new AccountService();
        String user=this.userNameField.getText();
        String pass=String.valueOf(passwrodField.getPassword());
        Account account=accountService.getAccount(user);
        if(account.getUserName()==null){
            noteLabel.setText("username or password wrong!!");
        }
        else if(account.getUserName().equals(user) && account.getPassword().equals(pass)){
            moneyField.setText(account.getMoney());
            double time= Double.parseDouble(account.getMoney())/(Double.parseDouble(priceField.getText()));
            timeField.setText(getTime(time));
            sigginDialog.setVisible(false);
            
        
        if(Double.parseDouble(account.getMoney())==0) noteLabel.setText("Het tien");
        Client client=new Client(1, 1, "7.9", 1, account.getUserName());
        clientMangement.updateClient(client);
        countMoney();
            
        this.setVisible(true);
        }
        else noteLabel.setText("username or password wrong!!");
        
        
       
        
        
        
        
        
    }//GEN-LAST:event_singinButtonActionPerformed
     public void countMoney()
    {   
        
        new Thread(){
            public void run()
            {while(Double.parseDouble(moneyField.getText())>0 && runing)
            { Double money=Double.parseDouble(moneyField.getText());
                Double price=Double.parseDouble(priceField.getText());
                try{sleep(1000*30);
                
                }
                catch(InterruptedException e)
                {
                    System.out.println(e);
                }
                money-=price/5;
                moneyField.setText(Double.toString(money));
                double time= money/(Double.parseDouble(priceField.getText()));
                timeField.setText(getTime(time));
                
            }
            if(Double.parseDouble(moneyField.getText())<=0)
            {
            logout();
            Account a=new Account(userNameField.getText(), String.valueOf(passwrodField.getPassword()), "0");
            accountService.updateAccount(a);
             Client c=new Client(1, 1, "7.9", 1,a.getUserName());
        clientMangement.updateClient(c);
                JOptionPane.showMessageDialog(null, "HẾT TIỀN");
            }
            }
        }.start();
    }
    
         
    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
       
        String userName=userNameField.getText();
        String pass=String.valueOf(passwrodField.getPassword());
        String money=moneyField.getText();
        Account a=new Account(userName, pass, money);
        accountService.updateAccount(a);
        Client c=new Client(1, 1, "7.9", 0, "");
        clientMangement.updateClient(c);
        runing=false;
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void inboxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inboxButtonActionPerformed
        // TODO add your handling code here:
        inboxDialog.setVisible(true);
    }//GEN-LAST:event_inboxButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendButtonActionPerformed

    private void serviceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceButtonActionPerformed
        // TODO add your handling code here:
        serviceDialog.setVisible(true);
    }//GEN-LAST:event_serviceButtonActionPerformed

    private void OrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderButtonActionPerformed
        // TODO add your handling code here:
        ListSelectionModel listSelectionModel=foodTable.getSelectionModel();
        listSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        Food food;
        int[] rows=foodTable.getSelectedRows();

        String name=String.valueOf(foodTable.getValueAt(rows[0], 1));
        String Price=String.valueOf(foodTable.getValueAt(rows[0], 2));
        String Kind=String.valueOf(foodTable.getValueAt(rows[0], 3));
        String food_id=String.valueOf(foodTable.getValueAt(rows[0], 0));

        OrderRecord orderRecord;

        orderRecord=new OrderRecord(1,food_id,1,name,"bomay1","2019/11/13",Price);
        String lenh="order";
       

        

    }//GEN-LAST:event_OrderButtonActionPerformed
    public void logout(){
        this.dispose();
    }
    private void moneyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyFieldActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_moneyFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CLient1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CLient1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CLient1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CLient1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CLient1().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OrderButton;
    private javax.swing.JTable foodTable;
    private javax.swing.JButton inboxButton;
    private javax.swing.JDialog inboxDialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField moneyField;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passwrodField;
    private javax.swing.JTextField priceField;
    private javax.swing.JButton sendButton;
    private javax.swing.JButton serviceButton;
    private javax.swing.JDialog serviceDialog;
    private javax.swing.JPanel servicePanel;
    private javax.swing.JDialog sigginDialog;
    private javax.swing.JButton singinButton;
    private javax.swing.JTextField timeField;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
